# Do not add items to the ITEMS section, the plugin will not see them, I will add this in the future!
Items:
  Trap:
    DisplayName: "&eTrap" # Display name
    Material: NETHERITE_SCRAP # Material - List of material: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
    despawn_delay: 120
    Lore:
      - "§f"
      - "  §fRarity: §eLegendary  "
      - "§f"
      - "  §fDescription:"
      - "   §fWhen using §7(RCB)§f"
      - "   §fplaces obsidian box §63x3"
      - "§f"
    onUse:
      - "[PLACESCHEM] trap1"
      - "[WAIT] 0.1"
      - "[PLACESCHEM] trap2"
      - "[WAIT] 0.1"
      - "[PLACESCHEM] trap3"
      - "[WAIT] 0.1"
      - "[PLACESCHEM] trap4"
      - "[WAIT] 0.1"
      - "[PLACESCHEM] trap5"
      - "[WAIT] 0.1"

  Plast:
    DisplayName: "&bPlast"
    Material: DRIED_KELP
    despawn_delay: 120
    Lore:
      - "§f"
      - "  §fRarity: §bUltra-Rare  "
      - "§f"
      - "  §fDescription:"
      - "   §fWhen using §7(RCB)§f"
      - "   §fplaces obsidian plast §63x3"
      - "§f"

Settings:
  checkForUpdates: true

Shematics:
  trap:
    file: "building/trap.scm"
  plast:
    file: "building/trap.scm"

DisabledRegions:
  - spawn


