# Do not add items to the ITEMS section, the plugin will not see them, I will add this in the future!
Items:
  Trap:
    DisplayName: "&eTrap" # Display name
    Material: NETHERITE_SCRAP # Material - List of material: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
    Lore:
      - "§f"
      - "  §fRarity: §eLegendary  "
      - "§f"
      - "  §fDescription:"
      - "   §fWhen using §7(RCB)§f"
      - "   §fplaces obsidian box §63x3"
      - "§f"
    onUse:
      - "[PLACESCHEM] trap1;120" # onUse condition
      - "[WAIT] 0.1"
      - "[PLACESCHEM] trap2;120"
      - "[WAIT] 0.1"
      - "[PLACESCHEM] trap3;120"
      - "[WAIT] 0.1"
      - "[PLACESCHEM] trap4;120"
      - "[WAIT] 0.1"
      - "[PLACESCHEM] trap5;120"
      - "[WAIT] 0.1"

  Plast:
    DisplayName: "&bPlast"
    Material: DRIED_KELP
    Lore:
      - "§f"
      - "  §fRarity: §bUltra-Rare  "
      - "§f"
      - "  §fDescription:"
      - "   §fWhen using §7(RCB)§f"
      - "   §fplaces obsidian plast §63x3"
      - "§f"
    onUse:
      - "[PLACESCHEM] plast1;120"
      - "[WAIT] 0.1"
      - "[PLACESCHEM] plast2;120"
      - "[WAIT] 0.1"
      - "[PLACESCHEM] plast3;120"
      - "[WAIT] 0.1"
      - "[PLACESCHEM] plast4;120"
      - "[WAIT] 0.1"
      - "[PLACESCHEM] plast5;120"
      - "[WAIT] 0.1"

Settings:
  checkForUpdates: true

Schematics:
  trap:
    file: "building/trap.scm"
  plast:
    file: "building/plast.scm"

DisabledRegions:
  - spawn


