# Do not add items to the ITEMS section, the plugin will not see them, I will add this in the future!


Settings:
  checkForUpdates: true

Schematics:
  trap:
    file: "building/trap.scm"
  plast:
    file: "building/plast.scm"

DisabledRegions:
  - spawn


