name: AnarchyUtils
version: '1.1'
description: 'My first plugin :) This plugin adds custom Trap and Plast'
main: my.toplib.anarchyutils.AnarchyUtils
api-version: '1.16'
load: POSTWORLD
author: TOPLIB
depend: [WorldEdit, WorldGuard]
commands:
  anarchy_utils:
    description: AnarchyUtils commands.
    usage: "Usage: /anarchy_utils <give/reload/info> <Trap | Plast> <Player>"
    aliases:
      - au
      - autils